"""init

Revision ID: 176860d704b0
Revises: 
Create Date: 2021-01-09 11:25:21.730785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176860d704b0'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('givenname', sa.String(length=128), nullable=True),
    sa.Column('surname', sa.String(length=128), nullable=True),
    sa.Column('personcode', sa.String(length=11), nullable=True),
    sa.Column('full_address', sa.String(length=512), nullable=True),
    sa.Column('docno', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('signature', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person'))
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=50), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_document_person_id_person')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_person_id'), 'document', ['person_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_person_id'), table_name='document')
    op.drop_table('document')
    op.drop_table('person')
    # ### end Alembic commands ###
